spring: 
  datasource: 
     url: ${MYSQL_CI_URL}
     username:  ${MYSQL_USER}
     password: ${MYSQL_PASSWORD}
     driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL 
    hibernate: 
      ddl-auto: create
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081
